package BiblioTech_AlpizarQuesada_ISemestre_2018;

import domain.Student;
import file.StudentFile;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.io.RandomAccessFile;

public class InternalFrame extends javax.swing.JInternalFrame {
    
        File archivo;

    public InternalFrame() {
        initComponents();
    }

    InternalFrame(BufferedImage bufferImage) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_namestudent = new javax.swing.JLabel();
        tf_nameStudent = new javax.swing.JTextField();
        lb_idStudent = new javax.swing.JLabel();
        lb_careerStudent = new javax.swing.JLabel();
        lb_yearStudent = new javax.swing.JLabel();
        lb_mailStudent = new javax.swing.JLabel();
        lb_celStudent = new javax.swing.JLabel();
        lb_adressStudent = new javax.swing.JLabel();
        tf_idStudent = new javax.swing.JTextField();
        tf_careerStudent = new javax.swing.JTextField();
        tf_yearStudent = new javax.swing.JTextField();
        tf_mailStudent = new javax.swing.JTextField();
        tf_celStudent = new javax.swing.JTextField();
        tf_adressStudent = new javax.swing.JTextField();
        btn_registerStudent = new javax.swing.JButton();
        lb_Student = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("prueba");
        setAlignmentX(1.0F);
        setAlignmentY(1.0F);

        lb_namestudent.setFont(new java.awt.Font("Tahoma", 2, 16)); // NOI18N
        lb_namestudent.setText("Nombre");
        lb_namestudent.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        tf_nameStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_nameStudentActionPerformed(evt);
            }
        });

        lb_idStudent.setText("Carné");

        lb_careerStudent.setText("Carrera");

        lb_yearStudent.setText("Año");

        lb_mailStudent.setText("Correo");

        lb_celStudent.setText("Telefono");

        lb_adressStudent.setText("Dirreción");

        tf_idStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_idStudentActionPerformed(evt);
            }
        });

        tf_careerStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_careerStudentActionPerformed(evt);
            }
        });

        tf_mailStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_mailStudentActionPerformed(evt);
            }
        });

        tf_celStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_celStudentActionPerformed(evt);
            }
        });

        tf_adressStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_adressStudentActionPerformed(evt);
            }
        });

        btn_registerStudent.setText("Registrar");
        btn_registerStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registerStudentActionPerformed(evt);
            }
        });

        lb_Student.setText("Studiante");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lb_namestudent, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44)
                                .addComponent(tf_nameStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lb_adressStudent)
                                .addGap(98, 98, 98)
                                .addComponent(tf_adressStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lb_mailStudent)
                                    .addComponent(lb_celStudent))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(93, 93, 93)
                                        .addComponent(tf_mailStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(107, 107, 107)
                                        .addComponent(tf_celStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lb_yearStudent)
                                .addGap(108, 108, 108)
                                .addComponent(tf_yearStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lb_idStudent)
                                    .addComponent(lb_careerStudent))
                                .addGap(72, 72, 72)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tf_idStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(tf_careerStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 210, Short.MAX_VALUE)
                                        .addComponent(btn_registerStudent)))))
                        .addGap(112, 112, 112))))
            .addGroup(layout.createSequentialGroup()
                .addGap(315, 315, 315)
                .addComponent(lb_Student, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(lb_Student)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_namestudent, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_nameStudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_idStudent)
                    .addComponent(tf_idStudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb_careerStudent)
                            .addComponent(tf_careerStudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(btn_registerStudent)))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_yearStudent)
                    .addComponent(tf_yearStudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_mailStudent)
                    .addComponent(tf_mailStudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(lb_celStudent))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(tf_celStudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_adressStudent)
                    .addComponent(tf_adressStudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(137, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_nameStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_nameStudentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_nameStudentActionPerformed

    private void tf_idStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_idStudentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_idStudentActionPerformed

    private void tf_careerStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_careerStudentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_careerStudentActionPerformed

    private void tf_mailStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_mailStudentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_mailStudentActionPerformed

    private void tf_adressStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_adressStudentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_adressStudentActionPerformed

    private void tf_celStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_celStudentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_celStudentActionPerformed

    private void btn_registerStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registerStudentActionPerformed
        Student registerStudent  =new Student(tf_nameStudent.getText(),tf_idStudent.getText(), tf_careerStudent.getText(),Integer.parseInt( tf_yearStudent.getText()), tf_celStudent.getText(), tf_mailStudent.getText(),tf_adressStudent.getText());
        try {
           archivo= new File("estudiante.dat");
           StudentFile su = new StudentFile(archivo);
           su.addEndRecord(registerStudent);
            
        } catch (IOException ex) {
            System.out.println("error");
        }
    
    }//GEN-LAST:event_btn_registerStudentActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_registerStudent;
    private javax.swing.JLabel lb_Student;
    private javax.swing.JLabel lb_adressStudent;
    private javax.swing.JLabel lb_careerStudent;
    private javax.swing.JLabel lb_celStudent;
    private javax.swing.JLabel lb_idStudent;
    private javax.swing.JLabel lb_mailStudent;
    private javax.swing.JLabel lb_namestudent;
    private javax.swing.JLabel lb_yearStudent;
    private javax.swing.JTextField tf_adressStudent;
    private javax.swing.JTextField tf_careerStudent;
    private javax.swing.JTextField tf_celStudent;
    private javax.swing.JTextField tf_idStudent;
    private javax.swing.JTextField tf_mailStudent;
    private javax.swing.JTextField tf_nameStudent;
    private javax.swing.JTextField tf_yearStudent;
    // End of variables declaration//GEN-END:variables
}
